### ISSUE TITLE
ko publish doesn't build with pcap included

### ISSUE THREAD

**Issue by Kuvesz** [google/ko#111]
Hi!

I have a small go code that uses github.com/google/gopacket/pcap and whenever I try to use ko publish on that code I get the following error:
```
ko publish ./cmd/websocketsource/
2019/11/28 12:09:33 Using base gcr.io/distroless/static:latest for github.com/knative/eventing-contrib/cmd/websocketsource
2019/11/28 12:09:34 Building github.com/knative/eventing-contrib/cmd/websocketsource
2019/11/28 12:09:34 Unexpected error running "go build": exit status 2
# github.com/knative/eventing-contrib/vendor/github.com/google/gopacket/pcap
vendor/github.com/google/gopacket/pcap/pcap.go:30:22: undefined: pcapErrorNotActivated
vendor/github.com/google/gopacket/pcap/pcap.go:52:17: undefined: pcapTPtr
vendor/github.com/google/gopacket/pcap/pcap.go:64:10: undefined: pcapPkthdr
```
All other images I tried build fine, any ideas? I looked it up and they say that it's because I don't have libpcap-dev installed, but I do have that. I would be grateful for any quick answer.

**Comment by jonjohnsonjr** [comment]
Hey, sorry I've been on vacation 🛳 🇲🇽 🌴 🌮 

I'm guessing this is because you need `CGO_ENABLED=1` and we default to disabling it: https://github.com/google/ko/blob/1c54dd6b3e5e9821467778f49c208a68ef00b1a5/pkg/build/gobuild.go#L171

The reason we do that is because we default to a base image that doesn't include libc to keep images as small as possible: https://github.com/google/ko/blob/1c54dd6b3e5e9821467778f49c208a68ef00b1a5/pkg/commands/config.go#L76

You can [override the base image](https://github.com/google/ko/tree/1c54dd6b3e5e9821467778f49c208a68ef00b1a5#overriding-the-default-base-image) (try `gcr.io/distroless/base`) we use and override CGO_ENABLED by just setting it in your environment:

```
GGO_ENABLED=1 ko publish ./cmd/websocketsource/
```

Let me know if that helps, we should probably document this somewhere 😅

**Comment by Kuvesz** [comment]
Nice, thanks I'll look into these as soon as I have the time. Hope you had a great vacation. :)

**Comment by Kuvesz** [comment]
Sorry I took so long, it worked in the end but it took me a lot of failures to notice that you put a typo in your command that I just copy pasted.  (Correct version: `CGO_ENABLED=1 ko publish ./cmd/websocketsource/`)
To be fair G and C are quite similar.  ¯\_(ツ)_/¯

**Comment by jonjohnsonjr** [comment]
> it took me a lot of failures to notice that you put a typo in your command that I just copy pasted

:man_facepalming: 

Thanks for following up. Sorry about that :smile:
