### ISSUE TITLE
Consider using fswatch for dep-notify

### ISSUE THREAD

**Issue by mattmoor** [google/ko#125]
http://emcrisostomo.github.io/fswatch/

**Comment by mattmoor** [comment]
Thanks to @jbeda for the pointer :D

**Comment by jonjohnsonjr** [comment]
Maybe worth poking around https://github.com/fsnotify/fsnotify/issues/11

**Comment by mattmoor** [comment]
@rhuss was saying in knative slack that fswatch works well on macOS

**Comment by rhuss** [comment]
We used fsnotify first for our hot-reload needs in https://github.com/knative/client/blob/db569fae177eb41d688399c33f2d9de64875568f/hack/build.sh#L200-L223 but it turned out to be totally untreliably on macOS (fake detects as well as non-detects). Since we switched to fswatch everything is working as expected.

**Comment by mattmoor** [comment]
watch is deprecated
