### ISSUE TITLE
ko builder and ko operator

### ISSUE THREAD

**Issue by feloy** [google/ko#132]
Hi all,

Thanks for this great tool!

I've played with ko recently, and created an image integrating this tool: https://github.com/feloy/ko-builder, to be exectued as Job in Kubernetes to build and deploy an app in a simple way.

I also created an operator that deploys this Job automatically from a very simple CRD: https://github.com/feloy/ko-operator and helps the rolling update of apps. I have some more ideas, like automatic update on git pushes for example.

A very nice feature would be that ko provides a library, so that I could integrate the ko job into the operator instead of running as a separate job :)

**Comment by jonjohnsonjr** [comment]
I think most of the relevant parts _are_ exposed as a library, you'd just have to piece some of it together.

The meat of the `ko` logic is here: https://github.com/google/ko/blob/c3a657a04ba76d25da9427cb6335ec6eb3ea4c41/pkg/resolve/resolve.go#L36

Wiring up the dependencies for that is a bit of a mess due to options handling (mostly to support [watch mode](https://github.com/google/ko#ko-apply---watch-experimental)), but [this file](https://github.com/google/ko/blob/master/pkg/commands/resolver.go#L310-L353) contains the bulk of that logic. Untangling all the CLI options and exposing them via some declarative (kubernetes) spec seems useful, but I'm not sure if that should live in this project.

If there's some piece of logic missing that is easy to extract and expose, we could definitely do that.
