### ISSUE TITLE
Support local kodata for remote source in local yaml

### ISSUE THREAD

**Issue by n3wscott** [google/ko#145]
There are times where I would like to ship an external go binary in a manifest but I also need to give it some files, but unless the binary is local I am unable to add new kodata to the image I am building.

See https://github.com/n3wscott/kbash as an example. It would be super sweet if I could point kodata as "./" and an integrator takes my binary (remotely) and applies their custom scripts.

**Comment by mattmoor** [comment]
I’m 👎on overriding kodata (for now), but I am in favor of namespacing it.

The gist of this is that we switched from having the binary path be ‘/ko-app’ to ‘/ko-app/{basename}’ which allows me to use ko base images, sort of.  The problem here is that kodata still collides.

I think my recommendation is two-fold:
1. Move to namespaced kodata directories e.g. /var/run/kodata/{basename}, and namespaced env vars {BASENAME}_KO_DATA_PATH
2. Use a symlink and the old env var for the topmost layer for back compat

**Comment by n3wscott** [comment]
I am fine with any solution. The goal is a manifest that points to a remote binary (like a consumer of kbash would do) and a local kodata dir (it would be sweet if it could just be the root dir)

so at the end of the day if it was as simple as having a yaml and a bash script and ko applying that.. it would be rad.
