### ISSUE TITLE
Add `pkg/v1/kind` for writing images to KinD

### ISSUE THREAD

**Issue by mattmoor** [google/ko#149]
I think we want something like:
https://github.com/google/go-containerregistry/tree/master/pkg/v1/daemon

... but to write it directly to KinD.

cc @BenTheElder for pointers on the best API.

I'd love to get some mechanism like this so that we can support something like: `KO_DOCKER_REPO=kind.local`

**Comment by BenTheElder** [comment]
> It's fine to use port 5000 for local testing, similar to 2375 for Docker (rather than using port 2376)
But as a way to access your cluster, to tunnel 5000 from the laptop to the master node ? Eww.

The expectation with kind is that these clusters are *local*. There is better tooling for remote clusters than kind etc...

For *local* usage, loopback w/o a cert is defacto for most applications and seems like a non-issue.

Docker usage without auth is more powerful anyhow. If you do that in a dind type cluster you've given root. `foo docker-env` with a "vm less" cluster is just unauthed root ...

Back on topic though, @mattmoor please let me know if you have further questions, and feel free to file issues w/ kind, email me etc.

I don't think we should implement `v1.Image` in the kind repo because googlecontainer tools depends on k/k, that's a total no-go dependency for us.

**Comment by mattmoor** [comment]
> because googlecontainer tools depends on k/k

Not anymore, we forked out the part we needed, and it should only have been `pkg/authn/k8schain` at that, anything else would prune the dep.

Honestly, it may be worth having a convo about how we put this together.  `ko` is where this originally came up, but `kaniko` and `buildpacks` both use this library (among others), so I could see them wanting to take advantage of the same library to interface with kind for local dev.

In the meantime we should probably just document that when working with KinD folks should use a registry like DockerHub. 😬

**Comment by tstromberg** [comment]
A tangentially related KEP to be aware of: https://github.com/kubernetes/enhancements/pull/1757

**Comment by markusthoemmes** [comment]
Will this be solved via #180 ?
