### ISSUE TITLE
We should consider having another user-scoped config.

### ISSUE THREAD

**Issue by mattmoor** [google/ko#173]
Currently we have `.ko.yaml` as a project-scoped configuration file and `KO_DOCKER_REPO` as user-scoped configuration, but it would be nice (especially when context switching projects) to be able to configure user-specific `ko` settings in some way.

The idea here would be to support `.ko.user.yaml` or something that could be put into `.gitignore` and would include a search path similar to  #172, but also include the user's home directory.  I believe that this can be done in a way that it complements `KO_DOCKER_REPO` (considering the existence of `viper.SetEnvPrefix`).

**Comment by jonjohnsonjr** [comment]
Agree. The flags for naming strategies were a mistake because the way you have to name images depends on the per-user KO_DOCKER_REPO, not the codebase. Similarly, things like os/arch are probably dependent on the end user.

I'd like to avoid polluting $HOME permanently by choosing the wrong convention (e.g. ~/.docker/...), but I don't know what the "correct" way to do this is... something something [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)? How does git work?

**Comment by mattmoor** [comment]
In another context, I am experimenting with a precedence, which would be the equivalent of:
1. `~/.ko.yaml`
2. `./.ko.yaml`
3. `../.ko.yaml`
...

I am also debating something like `.ko.user.yaml` that's separate so that it can be put into `.gitignore`... 🤔

**Comment by mattmoor** [comment]
Honestly, context switching between registries is awkward with `KO_DOCKER_REPO`.  Really I want this in my kube context 🙃

**Comment by mattmoor** [comment]
I really like where `mink` ended up FWIW, which blends `./.mink.yaml` with `~/.mink.yaml` and env vars via viper

I know you have thoughts :P

**Comment by seankhliao** [comment]
there's [`os.UserConfigDir`](https://pkg.go.dev/os#UserConfigDir) which saves our `$HOME` dirs from being cluttered
