### ISSUE TITLE
Please provide a sample

### ISSUE THREAD

**Issue by stevef1uk** [google/ko#18]
Hi,

Just trying this out with minkube as per your README. However, what is the expected contents of the config directory?

When I try the ko publish command for a very simple project  I am getting a ' error building "github.com/stevef1uk/helloworld-go": Get https://gcr.io/v2/token?scope=repository%3Adistroless%2Fstatic%3Apull&service=gcr.io: invoking docker-credential-gcloud: exit status 1; output: '

I have logged in to docker already so I am confused!

A simple example would help us newbies :-)

**Comment by jonjohnsonjr** [comment]
The config directory should container kubernetes manifests with go import paths instead of registry image references, as per [the example deployment](https://github.com/google/ko#the-ko-model). It seems like you've got that part correct.

From that error, we're failing to pull the base image ([gcr.io/distroless/static](https://gcr.io/distroless/static)). I suspect we're tripping over something in your auth config (`~/.docker/config.json`).

We're invoking the docker-credential-gcloud credential helper binary based on your config, which should have something like this in it:
```json
{
  "credHelpers": {
    "gcr.io": "gcloud"
  }
}
```

And that process is failing. The image is public, so there's probably an issue with that binary or the configuration. If you're just sideloading these images into minikube, it should be sufficient to just drop the `"gcr.io": "gcloud"` line from your config as a workaround.

I'm happy to help further but hopefully that's enough info to start debugging.

**Comment by stevef1uk** [comment]
Thanks. I created the example deployment, pointed it at my GitHub repo and it is deployed on qinikube successfully.
