### ISSUE TITLE
Deprecate installing ko from ./cmd/ko

### ISSUE THREAD

**Issue by n3wscott** [google/ko#258]
As one of `ko`'s biggest fans, it pains me to see people fail to install `ko` by trying:

```shell
go install github.com/google/ko
```

Because this repo is not likely to have more than one executable, let's move the binary to the root to make the logical install line above work as expected.

**Comment by antoineco** [comment]
Closed by #257?

**Comment by ImJasonH** [comment]
Can we also instead recommend installing from released binaries, instead of using `go install`?

Some user reports indicate this approach might lead to friction, since users should run the command outside of a directory that's part of a Go module, and might be broken by case-sensitivity bugs if some packages had previously been fetched on the user's machine.

Installing from prebuilt released binaries should be the default.

**Comment by jonjohnsonjr** [comment]
> Some user reports indicate this approach might lead to friction, since users should run the command outside of a directory that's part of a Go module, and might be broken by case-sensitivity bugs if some packages had previously been fetched on the user's machine.

I _think_ this is why @n3wscott filed https://github.com/google/ko/pull/288

Installing with go is broken such that you don't pick up the latest release, AFAICT.

**Comment by n3wscott** [comment]
Is there no issue to install the cmd version? I thought the casing issue is not related to where the exe is but a bad actor on the other lib

**Comment by jonjohnsonjr** [comment]
Jason's comment is unrelated to ./ko vs ./ko/cmd/ko AFAICT. Our releases are fine, but you can't install the latest release via `go` anymore, for some reason. I'm not sure how to fix this.
