### ISSUE TITLE
ko publish ./...

### ISSUE THREAD

**Issue by ImJasonH** [google/ko#273]
```
ko publish ./cmd/...
2020/12/19 09:39:01 failed to publish images: found 7 local packages, expected 1
```

`ko resolve` is  capable of building and deploying multiple images, and `ko publish` is seemingly capable of identifying multiple import paths to build, but we run afoul of https://github.com/google/ko/blob/722ad3c37b2e01219aa053ba11b6b0d6d065b5d7/pkg/commands/publisher.go#L39 in `ko publish`.

**Comment by ImJasonH** [comment]
FWIW `ko publish ./cmd/foo ./cmd/bar ./cmd/baz` works, it's just `./...` that doesn't. Maybe this was an explicit decision, but I don't remember the motivation.

I guess `ko publish ./...` has slightly different semantics ("publish all supported refs in `./...`") compared to `ko publish ./a ./b` ("publish `./a` and `./b`, _if they are supported_").

**Comment by jonjohnsonjr** [comment]
I don't think it was an explicit decision. Though... this reminds me of how we started requiring `ko://` in references because it made things a lot easier to reason about and error report, but I think it's probably fine to support this kind of thing, if the diff is reasonable. We should be able to find and build any main packages pretty cheaply... we might have to change some things from returning a `foo` to a `[]foo`, but I think that's fine.
