### ISSUE TITLE
`--platform` doesn't work if `GOOS` and `GOARCH` are set

### ISSUE THREAD

**Issue by mattmoor** [google/ko#274]
Today we *default* `--platform` to `$GOOS/$GOARCH`, but if these are set then the flag doesn't work (unless the value passed matches what's in GOOS/GOARCH, which defeats the purpose!).

The crux of the issue is that we always allow the current environment to override our CGO/GOOS/GOARCH settings because of the order here:
https://github.com/google/ko/blob/722ad3c37b2e01219aa053ba11b6b0d6d065b5d7/pkg/build/gobuild.go#L277

cc @jonjohnsonjr @ImJasonH

**Comment by mattmoor** [comment]
I noticed this because I had `GOOS=` and `GOARCH=` in my env, and this was clearing ko's setting, which resulted in ko producing darwin/arm64 binaries, which is not exactly what I wanted 🤣 

This is hugely problematic imo because we are now literally printing the platform/architecture we are targetting, and then letting the environment override things, which leads to silent failures.

**Comment by jonjohnsonjr** [comment]
> Today we default --platform to $GOOS/$GOARCH

Not exactly, we default to $GOOS/$GOARCH if they are set, and "linux/amd64" otherwise.

> The crux of the issue is that we always allow the current environment to override our CGO/GOOS/GOARCH settings because of the order here:

If we flip the order, we also need some way to set CGO_ENABLED=1, since we default otherwise. For goos/goarch this makes sense to me in most cases, but I think there should still be some way to override the platforms for a given base image. Consider the case where you broke kubernetes because we distroless changed from being platform-less in the config file to having the platform set. Prior to that, you could use `ko` to build for any platform by setting GOOS/GOARCH and using distroless/static, but that becomes ~impossible to do. I think it's generally useful to be able to override the goos/goarch to be different from the base image, even if just for testing purposes.

> I noticed this because I had GOOS= and GOARCH= in my env

I don't know if this is something we need to defend against, just you being dumb. Maybe we print a warning if --platform is set and GOOS/GOARCH are different? Maybe we allow you to override GOOS/GOARCH _only_ if your base image is _not_ multi-platform?

**Comment by mattmoor** [comment]
> Not exactly, we default to $GOOS/$GOARCH if they are set

Yes, I know.  The feature's only broken when those are set 😉 

If I run `ko publish --platform=linux/arm64` in an environment with `GOOS=darwin GOARCH=amd64` it tells me it's building `linux/arm64` and produces a binary for `darwin/amd64`.

I think your supposition is that most folks don't have GOOS/GOARCH set, but there are IDEs that set these up automatically in their embedded shells.  I know this because this has broken folks using ko before (macos -> linux), long before we added `--platform`.

Honestly, the cardinal precedence for CLI is flag > env > config, and we're violating that here (while lying to the user!).  I'd say that the answer to most of your commentary above is best resolved by having folks go through `--platform` and making it support the scenarios you care to support.  I doubt you are ever going to convince me that env > flag should be a thing. 🤷 


> the case where you broke kubernetes because distroless changed from being platform-less in the config file to having the platform set

Hmm, that's not what happened at all, but ok...


> I don't know if this is something we need to defend against, just you being dumb.

Ouch.

**Comment by jonjohnsonjr** [comment]
> Ouch.

Please read most of my response as tongue in cheek, not meant to actually offend :P sorry.

Is [this](https://github.com/google/ko/blob/cde258294ff7be831199f61e6f6e8cc6ed17f564/.travis.yml#L21) just completely broken?

> Honestly, the cardinal precedence for CLI is flag > env > config

Definitely agree with this argument. I'd be okay with swapping the env order if not for the CGO_ENABLED thing. Want to promote that to a flag? We _could_ just drop the user env entirely? What else in there contributes to go builds?

With either approach, what do we do about GOARM? Should we allow users to override that, or only ever use the image's platform? Should GOARM contribute to `--platform` defaulting if it's unset?

My argument isn't coming so much from a place of "I think the current behavior is reasonable" so much as "at some point in the past, we told people to use GOOS/GOARCH to work around the lack of multi-platform support, and I worry that just breaking that is bad practice".

How do you want to fix this? We could start with an error when `--platform` is used in conjunction with GOOS/GOARCH/GOARM? Maybe graduate that to just ignoring or filtering the user env?

**Comment by mattmoor** [comment]
> Is this just completely broken?

Yes 🤣 


> I worry that just breaking that is bad practice

I am still confused how we are breaking that, given that it forms the basis for the `--platform` default?

The main thing I see us breaking is `CGO_ENABLED=1`, which I'm unaware of anyone using, or any place documenting that we support this.  I do think a flag is a better option for this.

**Comment by jonjohnsonjr** [comment]
> The main thing I see us breaking is CGO_ENABLED=1, which I'm unaware of anyone using, or any place documenting that we support this. I do think a flag is a better option for this.

Sounds good to me -- I've been looking at how we can support this in https://github.com/google/ko/issues/261 a bit.

> I am still confused how we are breaking that, given that it forms the basis for the --platform default?

Because if your base image isn't an image index, the `--platform` flag is basically ignored, so we'd end up building for whatever we find in [the config file](https://github.com/google/ko/blob/552c3d43366ed603192627cc45ba5d71c02c10c9/pkg/build/gobuild.go#L460-L470), which might be _nothing_.

**Comment by mattmoor** [comment]
> the --platform flag is basically ignored

I think this is what I'd "fix".
