### ISSUE TITLE
Publish a `ko` builder with GCB's kubectl magic

### ISSUE THREAD

**Issue by mattmoor** [google/ko#4]
Basically this, but `ko`: https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/kubectl/kubectl.bash

cc @ImJasonH

**Comment by jonjohnsonjr** [comment]
@ImJasonH what does this have to do with go modules? Is this still relevant?

**Comment by ImJasonH** [comment]
The reason modules support was relevant is because without it the source
had to be made available in $GOPATH/src/<importpath>, which isn't going to
be the case in GCB or Tekton (or GitHub Actions).

gcr.io/cloud-builders/go did a bunch of funny business to symlink
`/workspace` into the correct location in GOPATH. But that won't be
necessary with modules.

Now that `ko` supports modules the source can be in `/workspace` and can
still be built. A `ko` image only needs to have `go` and `kubectl`, plus
the logic in kubectl.bash above to provide GKE creds.

We can get this done by having a base image that's `FROM golang`, installs
`kubectl`, renames it to `kubectl_real`, then has a `kubectl.bash` named
`kubectl` on PATH which sets up creds then calls `kubectl_real`. It's all a
terrible hack. Oh it also needs the GCR cred helper to push images. And
that's only enough to use ko against GKE/GCR.
