### ISSUE TITLE
ko publish --insecure-registry falls back to HTTP for communication

### ISSUE THREAD

**Issue by adambkaplan** [google/ko#488]
When the `--insecure-registry` option is passed to `ko publish`, ko falls back to using HTTP for image registry communication. This is problematic because some container registries (notably, OpenShift's internal registry) only publish HTTPS endpoints. Technically these image registries are secured - however they may be using untrusted/self-signed certificates.

Based on the work in #369 and #396, this behavior appears intentional to work with a local docker/distribution instance (ex - using KinD). Would it make sense to add a second `--tls-verify` flag, which defaults to `true`, but when `false` will ignore X.509 certificate errors?

**Comment by imjasonh** [comment]
Just to make sure I understand the issue, `--insecure-registry` toggles _both_ [`InsecureSkipVerify`](https://github.com/google/ko/blob/v0.9.3/pkg/publish/options.go#L117) (which you want), and [`name.Insecure`](https://github.com/google/ko/blob/v0.9.3/pkg/publish/default.go#L150) (skip TLS entirely and fallback to http; which you don't want). Is that correct?

This is a bit unfortunate, since it will be thorny to change the semantics of the existing `--insecure-registry` flag that people might be using. Adding a new flag, `--tls-skip-verify` (or `--tls-verify(=true)`) might also be confusing, and we'd have to be careful to document how the two interact.

Let me think about it some more and see if anything comes out of it.

cc @jonjohnsonjr

**Comment by adambkaplan** [comment]
> Just to make sure I understand the issue, `--insecure-registry` toggles _both_ [`InsecureSkipVerify`](https://github.com/google/ko/blob/v0.9.3/pkg/publish/options.go#L117) (which you want), and [`name.Insecure`](https://github.com/google/ko/blob/v0.9.3/pkg/publish/default.go#L150) (skip TLS entirely and fallback to http; which you don't want). Is that correct?

That is correct.

> Adding a new flag, `--tls-skip-verify` (or `--tls-verify(=true)`) might also be confusing, and we'd have to be careful to document how the two interact.

Indeed, that will be a challenge. My initial thought is to provide the following:

- New flag `--tls-skip-verify`, which toggles `InsecureSkipVerify`, we document this as "Use HTTPS, but skip verifying TLS certificates."
- Update the documentation for `--insecure-registry` to state `--tls-skip-verify` is effectively set to `true` (and will override any setting that is otherwise provided). Document as "Use HTTP and bypass any use of TLS encryption."

**Comment by adambkaplan** [comment]
Played around with this today, unfortunately we have a collision with a deprecated kubectl flag [--insecure-skip-tls-verify](https://github.com/google/ko/blob/main/internal/k8sflags.go#L40).

We _could_ go past deprecation and remove the flag, at the risk of breaking users who have untrusted kube apiservers :scream:.
