### ISSUE TITLE
unsupported platforms in resolve are ignored silently.

### ISSUE THREAD

**Issue by vaikas** [google/ko#582]
I was trying to figure out if I could build a /linux/arm64/v8 version (because tekton was looking for that, so figured I'd try... anyways). When I added that as a platform and things succeeded I felt pretty good about it. However, nothing seemed to happen to the image and using crane manifest shows that indeed it was not built.

I then was puzzled and tried something like this:
```
KO_DOCKER_REPO=ghcr.io/vaikas ko resolve --platform=linux/amd64,linux/arm64,linux/arm64/v8,something
```
I was kind of expecting that to complain about `something` somewhere during the process, but everything completed and that was just ignored.

**Comment by imjasonh** [comment]
This is probably pretty straightforward for `ko build`, but it might get complicated for `ko apply`/`ko resolve`, since there might be multiple base images involved, each with different supported platforms.

For example, Tekton builds some images with Windows support (`entrypoint` mainly), while lots of others aren't built for Windows (`controller`, `webhook`). So Tekton needs `ko resolve --platform=linux,windows` to work, even if some images never match `windows`.

In that case we could fail if none of the images in a `resolve` end up meaningfully using some platform, but that view of the resolve is pretty far from where platforms are matched and indexes get filtered. It'd probably have to be a total post-build, post-resolve failure, at which point maybe it's best just to warn instead?

I'll noodle on it a bit more, ideas welcome.
