### ISSUE TITLE
Multi-platform build targeting both amd64 and arm64

### ISSUE THREAD

**Issue by odsod** [google/ko#605]
**What are you trying to do?**

Trying to set up a build to output multi-platform images for both `linux/arm32v5` and `linux/amd64` for the same main entrypoint.

I can configure one or the other by changing the default base image between `gcr.io/distroless/static` and `gcr.io/distroless/static:latest-arm64`, but that requires changing the base image configuration between the build steps.

**What did you expect?**

Lacking a distroless/static image that supports all platforms, the ability to configure different base images for different platforms in the same build.

**Comment by imjasonh** [comment]
Yeah, this is a known annoyance. Some discussion and prototyping in https://github.com/google/ko/issues/475

Tekton also does this, to combine distroless and a Windows base image as a pre-step, but it's definitely annoying.

I think we could figure out how to make it work in ko directly.

**Comment by imjasonh** [comment]
Actually: Does this work for you?

```
ko publish ./cmd/app --platform=linux/amd64,linux/arm
```

If distroless/static supports armv5 I'd expect this to work.

**Comment by odsod** [comment]
@imjasonh Thank you, that seems to work!

So if I read this PR correctly I'm supposed to provide the ARM instruction set as part of the platform, https://github.com/google/ko/pull/239 - but that leads to a base image that is not included in the distroless/static metadata? 

So to solve this I can configure the build to target `linux/arm` and manually set `GOARM=5`?

**Comment by imjasonh** [comment]
You can specify `linux/arm/v5` to differentiate between variants if the base image specifies multiple (`linux/arm/v5`, `v7`, whatever). That PR means that the base image's detected/supported variant would be used to further specify better go compilation support if it can find it (using `GOARM`).

Since distroless only currently provides a generic `linux/arm`, this is moot. If you want to use another base image, eg alpine, you could.

If you want to support `linux/arm` via distroless/static and other variants via eg alpine, you could combine a base image together, like Tekton does as described in the issue above, but that's cumbersome. ko could do better.
