### ISSUE TITLE
create Makefile, Taskfile or justfile to provide common operations like lint, format, docgen

### ISSUE THREAD

**Issue by developer-guy** [google/ko#608]
There are a bunch of tools to support these kinds of operations, we should pick one of them and make it easier to run common operations like lint, format, docgen, etc.

* https://github.com/casey/just
* https://taskfile.dev/#/

cc: @imjasonh @mattmoor 

feel free to assign it to me, we(w/@dentrax) are willing to work on this

**Comment by imjasonh** [comment]
I'm not opposed to someone contributing this, but for my part, I probably wouldn't use it day-to-day. We've been just running scripts directly ourselves and checking things in CI, and that's been fine.

So I won't reject a Makefile/whatever being contributed, but I probably won't be surprised if it breaks in subtle ways in the future, unless someone is actively and regularly exercising it. This might lead to an even worse new contributor experience, since we could end up suggesting broken workflows. 😞 

wdyt?
