### ISSUE TITLE
Using a local docker registry

### ISSUE THREAD

**Issue by tanner-bruce** [google/ko#64]
I have a use case where we are running a local docker registry @ localhost:5000, and referencing the images in Kind/kubernetes as `host.docker.internal:5000`

If I set `KO_DOCKER_REPO=localhost:5000` I receive the following error:

```
2019/07/23 14:07:36 error creating publisher: failed to parse environment variable KO_DOCKER_REPO="localhost:5000" as repository: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: localhost:5000
```

Is something like this possible?

**Comment by jonjohnsonjr** [comment]
It's expecting a path, try:

`KO_DOCKER_REPO=localhost:5000/<some string>`

That will work fine for just publishing images, but if you want [`ko apply` and friends](https://github.com/google/ko/tree/3a0e70e520f93f16a3c1f6eb8058787d34d61886#ko-resolve) to work, you need to be able to push and pull images to/from the same registry (i.e. hostname).

There's also the [`--local` flag](https://github.com/google/ko/tree/3a0e70e520f93f16a3c1f6eb8058787d34d61886#with-minikube) if you just want to sideload images into your docker daemon (as `ko.local/...`) instead of running a registry, which could skirt around the hostname issues.

**Comment by tanner-bruce** [comment]
Thanks @jonjohnsonjr. That seems to have worked. I can get around this by modifying my hosts file.

I am now running into something that looks like an actual issue: adding `--insecure-skip-tls-verify` to the `ko` call results in this error:

```error: Unexpected args: [true]```

I have also made sure to add `host.docker.internal:5000` as an insecure registry in my docker config, is there something else I need to do?

**Comment by jonjohnsonjr** [comment]
Yeah, sorry, that one is going to be annoying to fix. You're running into https://github.com/google/go-containerregistry/issues/211 because we expect to use https for everything, only falling back to http in [certain scenarios](https://github.com/google/go-containerregistry/blob/e8c6a4993fa7c12b6ca56007739116b27ecb84c1/pkg/name/registry.go#L83). We allow http for `.local(host)` and `localhost:...` but not `.internal`.

We don't (yet) respect the docker config for insecure registries and `--insecure-skip-tls-verify` actually applies to the kubernetes API server, not the registry.

It would be interesting to see if we can hijack that flag and use it for the registry as well. You'd need to pass it down to the [publisher](https://github.com/google/ko/blob/3a0e70e520f93f16a3c1f6eb8058787d34d61886/pkg/publish/default.go#L98) and pass [name.Insecure](https://godoc.org/github.com/google/go-containerregistry/pkg/name#Insecure) into that `name.NewTag` call.

That would probably be confusing, though, since it wouldn't work for `ko publish`. We should probably just add a `--insecure-registry` flag to match docker's behavior.

Sorry I don't have a better answer, this is a longstanding issue that I haven't found the time or motivation to fix.

**Comment by tanner-bruce** [comment]
No worries! Would adding `.internal` to that logic be accepted in a PR?

I'lll take a peak at the `insecure-skip-tls-verify`, both why it is failing, and making it work with docker.

**Comment by jonjohnsonjr** [comment]
> Would adding .internal to that logic be accepted in a PR?

If you can point to an RFC or something as justification for `.internal`, I'm happy to merge it :smile: 

> why it is failing

I think `--insecure-skip-tls-verify` is actually working, it just only applies to kubectl.

> making it work with docker

Adding a separate flag to control registry behavior (e.g. `--insecure-registry`) would be much preferable to reusing the kubectl flag, since someone might want those values to be different.

**Comment by tanner-bruce** [comment]
> If you can point to an RFC or something as justification for .internal, I'm happy to merge it 

:D I really have nothing on that one.

I've got it working properly though.

![image](https://user-images.githubusercontent.com/21345430/61754485-58942100-ad81-11e9-8889-da7aeb11038c.png)

**Comment by tanner-bruce** [comment]
:)

I've got it working with an `--insecure-registry` flag.

![image](https://user-images.githubusercontent.com/21345430/61754554-a7da5180-ad81-11e9-8f0e-8f4d066a8f22.png)
