### ISSUE TITLE
how can I pass parameters to `go build` when exec `ko publish`

### ISSUE THREAD

**Issue by LinLshare** [google/ko#69]
In my Go project, I use `go build -tags 'dev'` to build dev version, and use `go build -tags 'prod'` to build production version. When I called `ko publish .`, it told me that `failed to publish images: importpath "git.xxx.com/my-project" is not supported`

I know that `ko` will call `go build`, but how can I pass `-tags 'dev'` to `go build` when exec `ko publish`?

**Comment by jonjohnsonjr** [comment]
We don't do a great job of passing through flags to the underlying `go build` invocation.

Somewhat related: https://github.com/google/ko/issues/54 and https://github.com/google/ko/issues/52

I dug around for a bit looking for the `go build -tags` parsing and ran across https://github.com/golang/go/commit/80e7832733fd245181af3394077f2df21303a4aa, which taught me two things:

1. This `tags` flag is changing from space-separated to comma-separated in 1.13. 
2. [`GOFLAGS`](https://golang.org/cmd/go/#hdr-Environment_variables) exists, which should let you work around this (for now).

Now, this isn't that great:

    $ GOFLAGS="-tags=dev" ko publish .

Ideally you could just do this:

    $ ko publish -tags=dev .

But that is going to be tough... we currently have another flag (`--tags, -t`) that allows you to specify how the image is tagged in your registry, so the way the above command is getting parsed right now is equivalent to:

    $ ko publish -t "ags=dev" .

This fails because `ags=dev` isn't a valid image tag. If we want to support that, we'll need to change how we handle flag parsing a bit. It might be possible to maintain a `go build` FlagSet, and do a first pass over argv before handing off flag parsing to cobra, but I haven't looked into it much.

I'm a little worried that the intersection of our flags, go's flags, and kubectl's flags is going to be a maintenance nightmare, but I'm sure we can figure something out.

**Comment by dprotaso** [comment]
What about an all encompassing flag for build args?

ie. `-build-args "-tag 'dev'"`

**Comment by dprotaso** [comment]
The above being a catch-all while more common options could should promoted to first level flags.

**Comment by jonjohnsonjr** [comment]
That doesn't seem like a big improvement over GOFLAGS.

**Comment by dprotaso** [comment]
I definitely missed the second point :(

Yeah I agree - GOFLAGS accomplishes that

**Comment by jonjohnsonjr** [comment]
I think `GOFLAGS` is sufficient for this for now, going to close this. Feel free to reopen if that doesn't work (or you have a better idea).

**Comment by cameronbraid** [comment]
GOFLAGS isnt sufficient for : `GOFLAGS="-ldflags=-Xmain.version=1.2.3"`

I get `flag provided but not defined: -Xmain.version`

**Comment by jonjohnsonjr** [comment]
> GOFLAGS isnt sufficient for : GOFLAGS="-ldflags=-Xmain.version=1.2.3"

Does this work?

`GOFLAGS="-ldflags=-X=main.version=1.2.3`

**Comment by cameronbraid** [comment]
Yep, thanks heaps

/cmd/server/main.go
```
package main
import (
	"fmt"
)
var Version = "dev"
func main() {
	fmt.Println("version " + Version)
}
```

```
go build ./cmd/server; ./server
```
prints `version dev`

```
go build -ldflags="-X=main.Version=1.2.3" ./cmd/server; ./server
```
prints`version 1.2.3`

```
x=`KO_DOCKER_REPO=ko.local GOFLAGS="-ldflags=-X=main.Version=1.2.3" ko publish ./cmd/server; docker run --rm -it $x
```
prints 
`version 1.2.3`
