### ISSUE TITLE
Fails when upgrading to 1.18

### ISSUE THREAD

**Issue by naveensrinivasan** [google/ko#713]
The http://github.com/ossf/scorecard project uses `ko` and we are in the process of upgrading to `1.18`. `ko` seems to have issues while upgrading to `1.18` https://github.com/ossf/scorecard/runs/6632670453?check_suite_focus=true#step:8:77

Any help would be appreciated.

Thanks

**Comment by imjasonh** [comment]
This doesn't seem related to 1.18, but rather `ko`'s dep on cosign, which is fairly old at 1.3.1 (current is 1.8.0). Between those two versions, the const was renamed. #718 should fix the issue.

The reason this causes problems is because you're `go install`ing `ko` in a module that also declares a dependency on cosign, and the newer dependency at that, so it's using your module's cosign dep to build `ko`, with the breaking API change.

You may have a better time installing `ko` from built releases, or having `go install`ed tools defined in a separate module for tools only.

**Comment by imjasonh** [comment]
> Thanks. This is from `tools` module. Our tooling is built around tooling module changing that and installing `ko` would be a significant change.
> 
> I see a PR with the fix and we will wait for that to be merged.

Ah, I see. Your [tools/go.mod](https://github.com/ossf/scorecard/blob/4a88dac00fc62a7ccc20ae8d70aea5db39856988/tools/go.mod#L273) has a dep on cosign 1.5.2, which also has the breaking API change. That was introduced in https://github.com/ossf/scorecard/pull/1560/ which looks to have only updated `ko`, so I'm not sure where that came from or why it breaks. 🤷 

In any case, after #718 you should be able to `go get -u github.com/google/ko@main` to pick it up and your build should work again.

Sorry for letting that dep get so far out of date, now that it's on a "real" release it should be dependabot'ed.
