### ISSUE TITLE
Unable to install the latest with updated cosign

### ISSUE THREAD

**Issue by naveensrinivasan** [google/ko#788]
We are trying to install `ko` with the latest `cosign` to avoid CVE, which is unable to install.

`../../../../../pkg/mod/github.com/google/ko@v0.11.2/pkg/build/gobuild.go:348:20: undefined: types.CycloneDXMediaType`

https://github.com/ossf/scorecard/pull/2143

**Comment by naveensrinivasan** [comment]
cc @imjasonh

**Comment by imjasonh** [comment]
This is fixed by https://github.com/google/ko/pull/667 which is not yet released.

When we release v0.12 (soon, hopefully) this should be resolved. In the meantime, you can `go install github.com/google/ko@main` or update [this line](https://github.com/ossf/scorecard/pull/2143/files#diff-11f03b0f97705b85807a720c4608013062002af3604f046a09a2571b0ae02554R9) to point to a commit after #667

**Comment by rashedkvm** [comment]
Thank you for the update, @imjasonh, I saw the same issue when upgrading to `github.com/sigstore/cosign@v1.10.1. Do you have any ETA for the release with #667 fix?

**Comment by naveensrinivasan** [comment]
@imjasonh  Thanks that worked!
