### ISSUE TITLE
ko resolve should exit error code when hitting 502 caused by docker repo issue

### ISSUE THREAD

**Issue by chaodaiG** [google/ko#84]
When hitting 502 caused by docker repo issue, `ko resolve` prints error message as stdout and exits 0, this should return non-zero exit code instead. The print line is [here](https://github.com/google/ko/blob/133ae27c6333361b1bbd7698a7f4867957ecdad4/pkg/commands/resolver.go#L206)

See example here: https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-serving-istio-1.1-mesh/1174030278339858432

Sample error message (Copy/pasted from link above):
```
2019/09/17 18:53:27 error processing import paths in "config/networking-istio.yaml": unsupported status code 502; body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>
```

**Comment by jonjohnsonjr** [comment]
Are you using `--watch`?

**Comment by chaodaiG** [comment]
Not afaik, unless implicitly. It's this file: https://github.com/knative/serving/blob/master/hack/generate-yamls.sh

**Comment by adrcunha** [comment]
All `ko` commands in the script above are something like:

```
ko resolve -P -f config/ --selector blablabla
```

**Comment by jonjohnsonjr** [comment]
Are you able to reproduce this reliably? I have a theory that the main thread is exiting with 0 after `	std.Output(2, fmt.Sprint(v...))` but before `os.Exit(1)` in [`log.Fatal`](https://golang.org/src/log/log.go#L317).

We could just add a `time.Sleep(1 * time.Millisecond)` [here](https://github.com/google/ko/blob/133ae27c6333361b1bbd7698a7f4867957ecdad4/pkg/commands/resolver.go#L241). Or maybe instead of doing log.Fatal and just returning [here](https://github.com/google/ko/blob/133ae27c6333361b1bbd7698a7f4867957ecdad4/pkg/commands/resolver.go#L207), we could send an error on `errCh` if `fo.Watch` is unset, otherwise `log.Printf`.

**Comment by jonjohnsonjr** [comment]
Actually we should probably just be using [errgroup](https://godoc.org/golang.org/x/sync/errgroup) and `Wait()` before exiting.

[This](https://github.com/google/ko/blob/133ae27c6333361b1bbd7698a7f4867957ecdad4/pkg/commands/resolver.go#L193) should just return an error, then we can handle it appropriately depending on if we're in watch mode or one-shot mode, instead of [this hack](https://github.com/google/ko/blob/133ae27c6333361b1bbd7698a7f4867957ecdad4/pkg/commands/resolver.go#L202-L205).

**Comment by chaodaiG** [comment]
> Actually we should probably just be using [errgroup](https://godoc.org/golang.org/x/sync/errgroup) and `Wait()` before exiting.
> 
> [This](https://github.com/google/ko/blob/133ae27c6333361b1bbd7698a7f4867957ecdad4/pkg/commands/resolver.go#L193) should just return an error, then we can handle it appropriately depending on if we're in watch mode or one-shot mode, instead of [this hack](https://github.com/google/ko/blob/133ae27c6333361b1bbd7698a7f4867957ecdad4/pkg/commands/resolver.go#L202-L205).

sgtm
